### ISSUE TITLE
Requirements for neakasa not found: ['alibabacloud_iot_api_gateway']

### ISSUE THREAD

**Issue by brintal** [timniklas/hass-neakasa#18]
Thanks a lot for your work on this integration.
Unfortunately I couldn't get it to work yet.

Installed via HACS like described and restarted HA, but when I try to add the integration via "Settings->Devices&Services->Add Integration" I get an Error 
"Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble". 
![image](https://github.com/user-attachments/assets/7bf35e54-3e43-4ac7-9fb2-16afeb0d4af1)

I checked the logs and the following error message shows up:

```
2024-12-07 20:49:44.164 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/.local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/.local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/.local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config_entries.py", line 1287, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config_entries.py", line 1312, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config_entries.py", line 1499, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config_entries.py", line 2964, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config_entries.py", line 2941, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/setup.py", line 575, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/local/lib/python3.12/site-packages/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/usr/local/lib/python3.12/site-packages/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/local/lib/python3.12/site-packages/homeassistant/requirements.py", line 264, in async_process_requirements
    self._raise_for_failed_requirements(name, missing)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/requirements.py", line 292, in _raise_for_failed_requirements
    raise RequirementsNotFound(integration, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for neakasa not found: ['alibabacloud_iot_api_gateway'].
```

I'm running 
Home Assistant Docker 2024.10.1
HACS 2.0.1

**Comment by brintal** [comment]
I was digging a bit further down in the logs and it seems the root cause is this:
```
2024-12-07 21:14:07.507 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package alibabacloud_iot_api_gateway: error: failed to remove file `/usr/local/lib/python3.12/site-packages/aiohappyeyeballs-2.4.3.dist-info/INSTALLER`
  Caused by: Permission denied (os error 13)
2024-12-07 21:14:09.087 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package alibabacloud_iot_api_gateway: error: failed to remove file `/usr/local/lib/python3.12/site-packages/aiohappyeyeballs-2.4.3.dist-info/INSTALLER`
  Caused by: Permission denied (os error 13)
2024-12-07 21:14:10.937 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package alibabacloud_iot_api_gateway: error: failed to remove file `/usr/local/lib/python3.12/site-packages/aiohappyeyeballs-2.4.3.dist-info/INSTALLER`
  Caused by: Permission denied (os error 13)
2024-12-07 21:14:12.577 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package alibabacloud_tea_util: error: failed to remove file `/usr/local/lib/python3.12/site-packages/aiohappyeyeballs-2.4.3.dist-info/INSTALLER`
  Caused by: Permission denied (os error 13)
2024-12-07 21:14:14.722 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package alibabacloud_tea_util: error: failed to remove file `/usr/local/lib/python3.12/site-packages/aiohappyeyeballs-2.4.3.dist-info/INSTALLER`
  Caused by: Permission denied (os error 13)
2024-12-07 21:14:16.312 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package alibabacloud_tea_util: error: failed to remove file `/usr/local/lib/python3.12/site-packages/aiohappyeyeballs-2.4.3.dist-info/INSTALLER`
  Caused by: Permission denied (os error 13)
```

**Comment by brintal** [comment]
#[128214](https://github.com/home-assistant/core/issues/128214)

**Comment by brintal** [comment]
Might be related to https://github.com/home-assistant/core/issues/128214

**Comment by timniklas** [comment]
Sounds like an issue with your docker installation, are you having issues with the requirements of other integrations too?
My installation with HASSOS 2024.12.0 seems to work just fine.

**Comment by timniklas** [comment]
Please reopen if the error is still present
